### ISSUE TITLE
Install Instructions

### ISSUE THREAD

**Issue by jwhitcraft** [iuscommunity/django_versionTracker#1]
Can we get an INSTALL document?  I'm not familiar with python and Django but I would like to run this locally.

Thanks.

**Comment by carlwgeorge** [comment]
Sorry that we never got around this.  The original author hasn't been involved with the IUS project in quite some time, and the remaining contributors (myself included) weren't familiar enough with Django to document this either.  We don't even use this software anymore, so I'm going to archive this repository.

If you still need something similar, I'd recommend https://github.com/release-monitoring/anitya, or using their public instance at https://release-monitoring.org.
